name: Wails build

#on: [ push, pull_request ]

on:
  push:
    tags:
      - "v*"
jobs:
  package:
    strategy:
      matrix:
        go-version: [ 1.19 ]
        os: [ macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Get Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Build Wails app
        run: |
          wails build

      - name: zip macos artifact
        if: matrix.os == 'macos-latest'
        run: |
          cd ./build/bin
          zip -r ./../../surreal_explorer_mac.zip ./SurrealDB\ Explorer.app

      - name: upload artifact macOS
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v2
        with:
          name: surreal_explorer_mac
          path: surreal_explorer_mac.zip

      - name: zip windows artifact
        if: matrix.os == 'windows-latest'
        run: |
          Compress-Archive -Path .\build\bin\surrealdb_explorer* -DestinationPath .\surreal_explorer_windows.zip

      - name: upload artifact windows
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v2
        with:
          name: surreal_explorer_windows
          path: surreal_explorer_windows.zip

  release:
    runs-on: ubuntu-latest
    needs: package
    steps:
      - name: Download macOS package
        uses: actions/download-artifact@v3
        with:
          name: surreal_explorer_mac

      - name: Download windows package
        uses: actions/download-artifact@v3
        with:
          name: surreal_explorer_windows

      - name: Display structure of downloaded files
        run: ls -R

      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          files: |
            ./surreal_explorer_mac.zip
            ./surreal_explorer_windows.zip
